sudo: false
language: node_js
node_js:
- '8'
- '7'
install:
  - yarn global add babel-cli
  - yarn global add coveralls
  - yarn install
after_success: yarn run coverage
deploy:
  provider: npm
  email: jeffrey.yan@outlook.com
  api_key:
    secure: X/rTkQRoIOJRlACC1iHktIMCmyq+sJMtxPOwOjiikc4pWLBGUddnjEXmXqTdcDncVO4QPhY7GbhS1fMi4vRhjMZdtFS61k2ZPhDxHGwhbX2DvRRGIHaaNKBTcCL8Bad0fE6/dWoVrCM63U/+bEKedq3e+uaEaca4EgmP6IpgF+8gMj/bOSIae8H8p5PgfR8S1tYqVyV9otrG1KeT/fsOUnv9EN3OeMzlP5Zv4Rk32oNPx7C/QZveCE7CMRBCZ0SE4hOGh8XDTq9U9cuOJy9aS+N2ile0V23J26/YzMdUdEtKJfOkuAdzvBp0EW7e0Mox/JccqGkP0eNJIpWP6fte0R+ITI+nPYPDHMevoiwvn65LinpzEmnMM2qyDSmvwFo+nWdiPNWo5wQMTfqIwKHMBYtFoiZydlBF4w4ogQMuZgpEWbm2QQaQL2azYmE8yn3kQAdQ4T65ZXfBVGVhfcbvoYbnsIO8ELR/r1nJdrxPKUBgALfXtLNmHnqt1QEhSVA3q0nIGPdlllXRJPdPWkqe4vUye4R9idArSdZcXEl8UyLnzqY/+is0AWWjYDD1dORgb/tmQKJod3eHSICujN3VNcDGQSx2MgoOZmBUZ717nmo1WZtIiA2f0aDrFZljKemjKpkfzNEDjdgDwytG1lCdIKWqhB/MSWIivdY24vi2Wfo=
  on:
    tags: true
    repo: tandg-digital/objection-filter